# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biografia',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='biografia',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
    ]
