# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160321_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='biografia',
            name='images',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
