# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_biografia_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='images',
        ),
        migrations.AddField(
            model_name='images',
            name='bio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Biografia'),
        ),
    ]
