# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160322_1931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
    ]
