# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20160322_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AddField(
            model_name='biografia',
            name='text_org',
            field=models.TextField(default='', verbose_name='Texto original'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Imagen'),
        ),
    ]
