# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20160323_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.AlterField(
            model_name='biografia',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Artista'),
        ),
        migrations.AlterField(
            model_name='efemeride',
            name='bio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Biografia'),
        ),
    ]
