# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20160325_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=70, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
