# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discoteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Artista')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nombre')),
                ('extraInfo', models.TextField(verbose_name='Informacion Extra')),
                ('link', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='biografia',
            name='songs',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Song'),
            preserve_default=False,
        ),
    ]
