# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20160325_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biografia',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='songs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Biografia'),
            preserve_default=False,
        ),
    ]
