# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20160325_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Cancion', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AddField(
            model_name='song',
            name='link_org',
            field=models.CharField(default='', max_length=100, verbose_name='Enlace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='efemeride',
            name='event',
            field=models.CharField(max_length=100, verbose_name='Efemeride'),
        ),
        migrations.AlterField(
            model_name='song',
            name='extraInfo',
            field=models.TextField(verbose_name='Informacion extra'),
        ),
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Enlace'),
        ),
    ]
