# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20160325_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=70, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='song',
            name='extraInfo',
            field=models.TextField(blank=True, verbose_name='Informacion extra'),
        ),
    ]
