# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20160325_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Discoteca')),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='songs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Biografia'),
        ),
    ]
