# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20160325_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nombre')),
                ('extraInfo', models.TextField(blank=True, verbose_name='Informacion extra')),
                ('link', models.CharField(max_length=100, verbose_name='Enlace')),
                ('link_org', models.CharField(max_length=100, verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'Cancion',
                'verbose_name_plural': 'Canciones',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='lamina',
            field=models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Lamina'),
        ),
        migrations.AddField(
            model_name='album',
            name='tapa',
            field=models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Tapa'),
        ),
        migrations.AddField(
            model_name='songalbum',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Album'),
        ),
    ]
