# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20160325_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.AddField(
            model_name='discoteca',
            name='albumes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Album'),
        ),
        migrations.AddField(
            model_name='songalbum',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Album'),
        ),
    ]
