# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_album_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='songString',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='songString_org',
            field=models.TextField(blank=True, verbose_name='Listado de canciones'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(verbose_name='A\xf1o'),
        ),
        migrations.RemoveField(
            model_name='discoteca',
            name='albumes',
        ),
        migrations.AddField(
            model_name='discoteca',
            name='albumes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Album'),
        ),
    ]
