# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20160328_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albumes'},
        ),
        migrations.RemoveField(
            model_name='discoteca',
            name='albumes',
        ),
        migrations.AddField(
            model_name='album',
            name='discoteca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Discoteca'),
            preserve_default=False,
        ),
    ]
