# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20160328_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='songalbum',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='songalbum',
            name='tituloPrincipal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo principal'),
        ),
    ]
