# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20160328_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songalbum',
            old_name='extraInfo',
            new_name='infoExtra',
        ),
        migrations.RemoveField(
            model_name='songalbum',
            name='link_org',
        ),
    ]
