# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_remove_album_songstring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='songString_org',
            new_name='songString',
        ),
    ]
