# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_auto_20160329_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='efemeridemes',
            name='monthNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='efemeridemes',
            name='month',
            field=models.CharField(max_length=10, verbose_name='Mes'),
        ),
    ]
