# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_auto_20160330_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='efemeridemes',
            name='texto_org',
            field=models.TextField(default='', verbose_name='Efemerides'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='efemeride',
            name='event',
            field=models.CharField(max_length=300, verbose_name='Efemeride'),
        ),
    ]
