# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_auto_20160330_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songalbum',
            name='numero',
        ),
    ]
