# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_remove_songalbum_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Enlace'),
        ),
    ]
