# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20160330_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biografia',
            name='text_org',
            field=models.TextField(verbose_name='Texto'),
        ),
    ]
