# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_auto_20160330_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.CharField(max_length=300, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='songalbum',
            name='link',
            field=models.CharField(max_length=300, verbose_name='Enlace'),
        ),
    ]
