# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_auto_20160330_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songalbum',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre'),
        ),
    ]
