# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_auto_20160330_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='link_org',
            field=models.CharField(max_length=300, verbose_name='Enlace'),
        ),
    ]
