# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_auto_20160331_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songalbum',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='songString_org',
            field=models.TextField(blank=True, verbose_name='Listado de canciones'),
        ),
        migrations.DeleteModel(
            name='SongAlbum',
        ),
    ]
