# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_auto_20160403_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['name'], 'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
    ]
