# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_auto_20160403_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biografia',
            options={'ordering': ['name'], 'verbose_name': 'Biografia', 'verbose_name_plural': 'Biografias'},
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripcion'),
        ),
    ]
