# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_auto_20160403_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/', verbose_name='Imagen')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('alb', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Album')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
