# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_imagealbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='yearEnd',
            field=models.IntegerField(blank=True, null=True, verbose_name='A\xf1o (Periodo final)'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='A\xf1o (Periodo inicio)'),
        ),
    ]
