# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_actividad_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='title',
            field=models.CharField(max_length=100, verbose_name='T\xedtulo'),
        ),
    ]
