# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_auto_20160521_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.ImageField(default='', upload_to='images/', verbose_name='Imagen')),
                ('act', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Actividad')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
