# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_auto_20160522_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadimage',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
    ]
