# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_auto_20160524_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
    ]
