# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 21:33
from __future__ import unicode_literals

from django.db import migrations, models
from django.core.validators import FileExtensionValidator


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_actividad_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.FileField(default='', upload_to='videos/', validators=[FileExtensionValidator(allowed_extensions='.mp4')], verbose_name='Video'),
        ),
    ]
