# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_auto_20160525_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Descripci\xf3n'),
        ),
    ]
