# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_auto_20160525_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='title',
            new_name='name',
        ),
    ]
