# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_auto_20160525_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
