# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-08-02 23:19
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_auto_20170413_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
