# Generated by Django 2.2.3 on 2019-10-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_albumsong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='songString',
        ),
        migrations.RemoveField(
            model_name='album',
            name='songString_org',
        ),
    ]
