# Generated by Django 2.2.3 on 2019-10-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_auto_20191013_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='discoteca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='web.Discoteca'),
        ),
    ]
