# Generated by Django 2.1.15 on 2020-07-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_auto_20191013_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='bio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Biografia'),
        ),
    ]
