# Generated by Django 2.1.15 on 2020-07-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0072_auto_20200712_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadimage',
            name='act',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Actividad'),
        ),
        migrations.AlterField(
            model_name='biografia',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Artista'),
        ),
        migrations.AlterField(
            model_name='discoteca',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Artista'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Actividad'),
        ),
    ]
