# Generated by Django 2.1.15 on 2020-10-16 17:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0073_auto_20200712_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoActividad',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Actividad')),
            ],
            options={
                'verbose_name': 'Actividad del pago',
                'verbose_name_plural': 'Actividades del pago',
            },
            bases=('web.actividad',),
        ),
        migrations.RemoveField(
            model_name='albumsong',
            name='album',
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='text_org',
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.TextField(choices=[('A', 'Pago actividad'), ('P', 'Actividad')], default='A'),
        ),
        migrations.AlterField(
            model_name='biografia',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.FileField(default='', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Video'),
        ),
        migrations.DeleteModel(
            name='AlbumSong',
        ),
    ]
